command: ["python", "app.py"]

env:
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/seu-warehouse-id"   # << substitua pelo seu warehouse

permissions:
  - level: "CAN_USE"
    group_name: "users"
